"""initial schema with uv and uuid changes

Revision ID: fb0e3ecbaa70
Revises:
Create Date: 2026-10-06 12:37:37.979807

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fb0e3ecbaa70"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "airlines",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("iata_code", sa.String(length=2), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_airlines_iata_code"), "airlines", ["iata_code"], unique=True)
    op.create_table(
        "airports",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("iata_code", sa.String(length=3), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column("country", sa.String(length=60), nullable=False),
        sa.Column("country_code", sa.String(length=2), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_airports_country_code"), "airports", ["country_code"], unique=False)
    op.create_index(op.f("ix_airports_iata_code"), "airports", ["iata_code"], unique=True)
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("first_name", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "routes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("origin_id", sa.String(length=36), nullable=False),
        sa.Column("destination_id", sa.String(length=36), nullable=False),
        sa.Column("departure_date", sa.Date(), nullable=False),
        sa.Column("return_date", sa.Date(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.ForeignKeyConstraint(
            ["destination_id"],
            ["airports.id"],
        ),
        sa.ForeignKeyConstraint(
            ["origin_id"],
            ["airports.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_routes_destination_id"), "routes", ["destination_id"], unique=False)
    op.create_index(op.f("ix_routes_origin_id"), "routes", ["origin_id"], unique=False)
    op.create_index(op.f("ix_routes_user_id"), "routes", ["user_id"], unique=False)
    op.create_table(
        "flight_prices",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("route_id", sa.Integer(), nullable=False),
        sa.Column("airline_id", sa.String(length=36), nullable=False),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("currency", sa.Enum("PLN", "EUR", "USD", "GBP", name="currency"), nullable=False),
        sa.Column("departure_date", sa.Date(), nullable=False),
        sa.Column("return_date", sa.Date(), nullable=True),
        sa.Column("fetched_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.ForeignKeyConstraint(
            ["airline_id"],
            ["airlines.id"],
        ),
        sa.ForeignKeyConstraint(
            ["route_id"],
            ["routes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_flight_prices_fetched_at"), "flight_prices", ["fetched_at"], unique=False)
    op.create_table(
        "price_alerts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("route_id", sa.Integer(), nullable=False),
        sa.Column("threshold_price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("currency", sa.Enum("PLN", "EUR", "USD", "GBP", name="currency"), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_notified_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["route_id"],
            ["routes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("route_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("price_alerts")
    op.drop_index(op.f("ix_flight_prices_fetched_at"), table_name="flight_prices")
    op.drop_table("flight_prices")
    op.drop_index(op.f("ix_routes_user_id"), table_name="routes")
    op.drop_index(op.f("ix_routes_origin_id"), table_name="routes")
    op.drop_index(op.f("ix_routes_destination_id"), table_name="routes")
    op.drop_table("routes")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_airports_iata_code"), table_name="airports")
    op.drop_index(op.f("ix_airports_country_code"), table_name="airports")
    op.drop_table("airports")
    op.drop_index(op.f("ix_airlines_iata_code"), table_name="airlines")
    op.drop_table("airlines")
    # ### end Alembic commands ###
